project:
  type: website

website:
  title: "Jorge Velez"
  open-graph: true
  navbar:
    right:
      # - href: index.qmd
      #   text: Home
      - href: algorithms.qmd
        text: Algorithms
      - href: cs421.qmd
        text: Progrmg Languages & Compilers
      # - href: rl.qmd
      #   text: Reinforcement Learning 
      - href: cs.qmd
        text: Computer Science
      - href: finance.qmd
        text: Finance 
      - href: about.qmd
        text: About


format: 
  html:
    theme: cosmo
    css: styles.css
    # toc: true
    code-fold: true
    highlight-style: github
    jupyter: python3
    

