# To my family


My father was born in 1958 in Chiquintad, a small town in Ecuador. He came from a traditional farming family, which included his parents and one brother at that time later to include 14 other siblings. Growing up in poverty, far removed from city life, he was compelled to leave school in the second grade to help support his family by working on the farm. As a result, his education was limited, with minimal development in reading, writing, and almost no knowledge of mathematics or science.

In search of better opportunities and to fulfill his dreams, my father immigrated to the United States in 1992.

My mother was born in 1962 in Cuenca, a quaint city in Ecuador. She was one of six children in her family. During a simpler, seemingly smaller world, she was able to attend school up to the high school level. She met my father through my uncle, her brother, who was a friend of my father.

Around 1990, my parents welcomed their first child, my brother, marking the beginning of their journey as parents.